### ISSUE TITLE
안녕하세요?!

### ISSUE THREAD

**Issue by ryuda** [mu29/mu29.github.io#1]
안녕하세요~
클리앙에서 오픈소스 글 올려주신거 보고 들어왔어요~
혹시 실례가 안된다면 mu29.github.io 사이트 페이지 상단에 카테고리 검색, 태그검색 기능을
어떻게 구현했는지 알 수 있을까요? ^^;;
저도 픽사님 처럼 github.io를 멋들어지게 만들어 보고 싶네요ㅎㅎ

좋은하루되세요~

**Comment by mu29** [comment]
안녕하세요.
제가 직접 구현한 건 아니고, hexo라는 블로깅 툴과 tranquilpeak 테마를 사용했습니다 :)
